import { Pressable, Text, TouchableOpacity, View, StyleSheet, TextInput } from "react-native";
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useState } from "react";
import { FlatList } from "react-native";
import { event } from "react-native/types_generated/Libraries/Animated/AnimatedExports";

const storeData = async (value: string) => {
  try {
    await AsyncStorage.setItem('my-key', value);
  } catch (e) {
    // saving error
  }
  console.log("store data touched.")
};

const getData = async () => {
  try {
    const value = await AsyncStorage.getItem('my-key');
    if (value !== null) {
      // value previously stored
      // We're expecting a string depicting an array of objects, this removes it from string form.
      let arrObjects = JSON.parse(value)
      return (arrObjects)
    }
  } catch (e) {
    // error reading value
  }
  console.log("get data touched.")
};


//-------------------

const Index = () => {

  const refill = [
    {
      id: 'task1',
      desc: 'First Item',
    },
    {
      id: 'task2',
      desc: 'Second Item',
    },
  ];
  
  // After react mounts retrieve the data saved locally & set it.
  useEffect(() => {
    const fetchData = async () => {
      let DATA = await getData()

      setList(DATA)
    }

    fetchData()
  }, [])

  // For keeping track of To-Dos
  const [listData, setList] = useState('...');
  
  // For adding To-Dos, the initial states act as a placeholder - dont ask why.
  const [taskName, setTaskName] = useState('Task Name:')
  const [taskDesc, setTaskDesc] = useState('Task Desc:')
  const [taskDate, setTaskDate] = useState('Task Date:')

  // variable handle delete is equal to a function that does ...
  const handleDelete = (id: string) => {
    const newData = listData.filter(item => item.id !== id)
    setList(newData)
    
    // If you console log listData it still returns all items even after deleting one.
    // to get around this we'll ignore the state var and save the newData var we just created.
    console.log(listData)
    
    storeData(JSON.stringify(newData))
  }

  const handleAdd = () => {
    // I have zero fucking clue why i had to stringify something thats already a string but if it works it works
    const currentData = JSON.parse(JSON.stringify(listData))
    let number_of_tasks = currentData.length

    // currentData is 0th indexed so just add to the end by taking the length of the array/object.
    currentData[number_of_tasks] = JSON.parse(task)
    storeData(JSON.stringify(currentData))
    console.log(currentData)

    console.log(task)
    setList(currentData)
  }


  const CreateTask = () => {
    return(
      <View>
        <TextInput
            style={styles.input}
            placeholder={taskName}
            onSubmitEditing={(event) => { console.log( event.nativeEvent.text), setTaskName(event.nativeEvent.text) } }
          />
          <Pressable onPress={() => handleAdd()}>
            <Text>Add to list</Text>
          </Pressable>
      </View>
    )
  }

  // Will reuse some of this code for shared/given tasks generated by other users.
  const LocalTaskCreator = () => {
    return(
      <View>
        <TextInput
          style={styles.input}
          placeholder={taskName}
          onSubmitEditing={(event) => {setTaskName(event.nativeEvent.text)}}
        />
        <TextInput
          style={styles.input}
          placeholder={taskDesc}
          onSubmitEditing={(event) => {setTaskDesc(event.nativeEvent.text)}}
        />
        <TextInput
          style={styles.input}
          placeholder={taskDate}
          onSubmitEditing={(event) => {setTaskDate(event.nativeEvent.text)}}
        />
        <Pressable onPress={() => {console.log("You added a new task!"), LocalHandleAdd()}}>
            <Text>Create To-Do!</Text>
          </Pressable>
      </View>
    )
  }

  const LocalHandleAdd = () => {

    let compiledInfo = {id: `${taskName}`, desc: `${taskDesc}`, date:`${taskDate}`}
    console.log(compiledInfo)
    let temp = JSON.stringify(compiledInfo)
    console.log(temp)

    // I have zero fucking clue why i had to stringify something thats already a string but if it works it works
    const currentData = JSON.parse(JSON.stringify(listData))
    let number_of_tasks = currentData.length

    // currentData is 0th indexed so just add to the end by taking the length of the array/object.
    currentData[number_of_tasks] = JSON.parse(temp)
    storeData(JSON.stringify(currentData))
    console.log(currentData)

    setList(currentData)
  }

  return (
    <>
    <View
      style={{
        flex: .8,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Text>Hello world!</Text>
      <Pressable onPress={() => storeData(JSON.stringify(listData))}>
        <Text>save</Text>
      </Pressable>
      <Pressable onPress={() => getData()}>
        <Text>get</Text>
      </Pressable>
      <Text>-----------------------------------------</Text>
      <FlatList data={listData} renderItem={({item}) => (
        <View>
          <Text>{item.id}</Text>
          <Text>{item.desc}</Text>
          <Text>{item.date}</Text>
          <Pressable onPress={() => handleDelete(item.id)}>
            <Text>click to delete item</Text>
          </Pressable>
        </View>
      )}/>
      <Text>------------------------------------------</Text>
      <Pressable onPress={() => {setList(refill), storeData(JSON.stringify(refill))}}>
        <Text>Refill data</Text>
      </Pressable>
      {/* <CreateTask></CreateTask> */}
      <LocalTaskCreator/>
    </View>
  </>
  )
};

const styles = StyleSheet.create({
  input: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
});

export default Index;